#Build config validation
version: ~> 1.0

# Linguagem Utilizada para Desenvolver a Aplicação
language: python

# Versão que a aplicação suporta.
python:
  - "3.7.9"

#Build Environments
os: linux
dist: xenial

before_install:
  - openssl aes-256-cbc -K $encrypted_78159770279c_key -iv $encrypted_78159770279c_iv
    -in lab-devops-cloud-e2c2da9aee66.json.enc -out ../lab-devops-cloud-e2c2da9aee66.json
    -d
addons:
  sonarcloud:
    organization: "adrsant-labs"
    token:
      secure: $SONAR_TOKEN

jobs:
  include:
    - stage: Build

      name: "Testes Unitarios"
      # Instalação de Módulos que são necessários para a Aplicação.
      install:
        - pip install flask flask-wtf coverage
      script: # Defini o script de Teste que deve rodar toda vez que o código for alterado.
        - coverage run test.py || travis_terminate 1;
        - coverage report app.py || travis_terminate 1;
        - coverage xml app.py || travis_terminate 1;
        - sonar-scanner

    - stage: STG Deploy
      script: skip
      # Deploy no ambinte de staging (heroku)
      deploy:
        provider: heroku
        strategy: api
        api_key: $HEROKU_API_KEY
        edge: true
        app: devopslab-adrsant
        on:
          branch: master

    - stage: STG TEST
      script:
        - curl https://devopslab-adrsant.herokuapp.com/ | grep Hello || travis_terminate 1;

    - stage: PROD Deploy
      script: skip
      # Deploy no ambinte de production (Google Cloud)
      deploy:
        provider: gae
        keyfile: ../lab-devops-cloud-e2c2da9aee66.json
        project: coherent-window-314223
        on:
          branch: master

    - stage: PROD TEST
      script:
        - curl https://coherent-window-314223.uc.r.appspot.com/ | grep Hello || travis_terminate 1;